spring.application.name=restaurant
server.port=8090
spring.config.import=optional:classpath:.env.properties

# Datasource H2 (In-memory database - ไม่ต้องตั้งค่า PostgreSQL)
spring.datasource.url=jdbc:h2:mem:restaurantdb
spring.datasource.driver.class.name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JWT Configuration
jwt.secret=a34ece4e6bf181fdedf4c545bc7c138ad2d96ac39781f87a166a038c34893068
jwt.expiration=3600000

# Logging
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.org.hibernate=warn
logging.level.ku.cs.restaurant.listener.AuthenticationEventListener=debug
logging.file.name=log/restaurant-api.log
